import type { PhaseDocument, UserStory } from "./types"

export const phaseDocuments: PhaseDocument[] = [
  {
    id: "00_scope",
    title: "Escopo",
    phase: "Fase 0",
    status: "approved",
    dependsOn: [],
    blocks: ["01_tech_stack", "04_epics", "06_versions", "07_architecture"],
    purpose: "Define o app desktop, seus limites e a pasta monitorada.",
  },
  {
    id: "01_tech_stack",
    title: "Tech Stack",
    phase: "Fase 0",
    status: "approved",
    dependsOn: ["00_scope"],
    blocks: ["02_security", "05_principles", "10_environments"],
    purpose: "Registra Vite, React, TypeScript, Tailwind e shadcn/ui.",
  },
  {
    id: "02_security",
    title: "Segurança",
    phase: "Fase 0",
    status: "approved",
    dependsOn: ["00_scope", "01_tech_stack"],
    blocks: ["03_user_types", "05_principles"],
    purpose: "Define riscos e limites de segurança para a versão local.",
  },
  {
    id: "03_user_types",
    title: "Tipos de Usuário",
    phase: "Fase 0",
    status: "approved",
    dependsOn: ["02_security"],
    blocks: ["04_epics", "05_principles", "06_versions", "07_architecture"],
    purpose: "Define o Manager do Processo e demais perfis iniciais.",
  },
  {
    id: "04_epics",
    title: "Epics",
    phase: "Fase 1",
    status: "approved",
    dependsOn: ["00_scope", "03_user_types"],
    blocks: ["07_architecture"],
    purpose: "Agrupa capacidades do produto.",
  },
  {
    id: "05_principles",
    title: "Princípios de Código",
    phase: "Fase 1",
    status: "approved",
    dependsOn: ["01_tech_stack", "02_security", "03_user_types"],
    blocks: ["07_architecture"],
    purpose: "Define onde vivem dados, validações e componentes.",
  },
  {
    id: "06_versions",
    title: "Versões",
    phase: "Fase 1",
    status: "approved",
    dependsOn: ["00_scope", "03_user_types"],
    blocks: ["07_architecture", "08_database"],
    purpose: "Define v0 Foundation, v1 Folder Monitor e v2 Visual Studio Bridge.",
  },
  {
    id: "07_architecture",
    title: "Arquitetura",
    phase: "Fase 2",
    status: "pending",
    dependsOn: [
      "00_scope",
      "01_tech_stack",
      "02_security",
      "03_user_types",
      "05_principles",
      "06_versions",
    ],
    blocks: ["08_database", "09_api_contracts", "10_environments"],
    purpose: "Detalhar estrutura do app e estratégia de estado.",
  },
  {
    id: "08_database",
    title: "Banco de Dados",
    phase: "Fase 3",
    status: "pending",
    dependsOn: ["03_user_types", "06_versions", "07_architecture"],
    blocks: ["09_api_contracts"],
    purpose: "Fora do escopo inicial sem banco.",
  },
  {
    id: "09_api_contracts",
    title: "Contratos de API",
    phase: "Fase 3",
    status: "pending",
    dependsOn: ["03_user_types", "07_architecture", "08_database"],
    blocks: [],
    purpose: "Fora do escopo inicial sem API.",
  },
  {
    id: "10_environments",
    title: "Ambientes",
    phase: "Fase 3",
    status: "pending",
    dependsOn: ["01_tech_stack", "07_architecture"],
    blocks: [],
    purpose: "Documentar comandos locais e setup.",
  },
  {
    id: "11_decisions",
    title: "Log de Decisões",
    phase: "Contínuo",
    status: "approved",
    dependsOn: [],
    blocks: [],
    purpose: "Registro append-only das decisões do app desktop.",
  },
]

export const userStories: UserStory[] = [
  {
    id: "US-001",
    title: "Abrir app Meridian localmente",
    epic: "EPIC-01",
    version: "v0",
    status: "✅",
    moscow: "Must",
    dependsOn: [],
    doneWhen: "App roda com pnpm dev e renderiza layout inicial profissional.",
  },
  {
    id: "US-002",
    title: "Ver documentos de fase e status",
    epic: "EPIC-02",
    version: "v0",
    status: "✅",
    moscow: "Must",
    dependsOn: ["US-001"],
    doneWhen: "Lista de documentos exibe status, dependências e bloqueios básicos.",
  },
  {
    id: "US-003",
    title: "Configurar Git e qualidade local",
    epic: "EPIC-01",
    version: "v0",
    status: "✅",
    moscow: "Must",
    dependsOn: ["US-001"],
    doneWhen: "Git, gitignore, Prettier, Husky e lint-staged estão configurados.",
  },
  {
    id: "US-004",
    title: "Separar protocolo universal e app desktop",
    epic: "EPIC-01",
    version: "v0",
    status: "✅",
    moscow: "Must",
    dependsOn: ["US-001"],
    doneWhen:
      "meridian.md fica na raiz como protocolo universal e o app Vite fica em app-desktop.",
  },
  {
    id: "US-005",
    title: "Criar skills iniciais em .agent",
    epic: "EPIC-05",
    version: "v0",
    status: "✅",
    moscow: "Must",
    dependsOn: ["US-004"],
    doneWhen:
      ".agent/skills contém skills iniciais para agentes usarem junto com .agent/MERIDIAN.md.",
  },
  {
    id: "US-006",
    title: "Organizar camada operacional .agent",
    epic: "EPIC-05",
    version: "v0",
    status: "✅",
    moscow: "Must",
    dependsOn: ["US-005"],
    doneWhen:
      ".agent contém agents, skills, workflows, rules e scripts no padrão Meridian.",
  },
  {
    id: "US-007",
    title: "Alinhar kit .agent ao padrão Antigravity",
    epic: "EPIC-01",
    version: "v0",
    status: "✅",
    moscow: "Must",
    dependsOn: ["US-006"],
    doneWhen:
      "README.md na raiz, rules always_on, meridian-routing e workflows com $ARGUMENTS existem no kit.",
  },
]
