export type CommandHelpEntry = {
  id: string
  title: string
  commandId: string
  paletteTitle: string
  group: "views" | "governance" | "kit" | "planned"
  summary: string
  details: string[]
  outputChannel?: string
  icon?: string
  status: "shipped" | "stub"
}

export const COMMAND_HELP_GROUPS: { id: CommandHelpEntry["group"]; label: string }[] = [
  { id: "views", label: "Views (editor tabs)" },
  { id: "governance", label: "Governance & diagnostics" },
  { id: "kit", label: "Kit (agents & slash commands)" },
  { id: "planned", label: "Planned (v5)" },
]

export const MERIDIAN_COMMAND_CATALOG: CommandHelpEntry[] = [
  {
    id: "install-kit",
    title: "Install harness",
    commandId: "meridian.installKit",
    paletteTitle: "Meridian: Install Harness",
    group: "kit",
    summary: "Copy bundled Meridian kit (.agent/) into the workspace",
    details: [
      "Manual only — run from status bar, Command Palette, or Meridian → Commands.",
      "Copies agents, skills, workflows, and scripts from the VSIX bundle.",
      "Syncs .cursor/ and .claude/ IDE adapters via sync_cursor_kit.sh.",
    ],
    outputChannel: "Meridian Tools",
    icon: "$(cloud-download)",
    status: "shipped",
  },
  {
    id: "upgrade-kit",
    title: "Upgrade harness",
    commandId: "meridian.upgradeKit",
    paletteTitle: "Meridian: Upgrade Harness",
    group: "kit",
    summary: "Replace existing .agent/ with the bundled kit version",
    details: [
      "Overwrites .agent/ and re-runs adapter sync.",
      "Use after updating the extension to pick up kit changes.",
    ],
    outputChannel: "Meridian Tools",
    icon: "$(cloud-upload)",
    status: "shipped",
  },
  {
    id: "board",
    title: "Open Board",
    commandId: "meridian.openBoard",
    paletteTitle: "Meridian: Open Board",
    group: "views",
    summary: "Read-only kanban from docs/us/*.md",
    details: [
      "Project row (first toolbar line): active name, docs/ path, US count; dropdown when several products.",
      "Columns: Todo, Partial, Tests, Done, and Frozen (toggle).",
      "Version and epic filters (All / None / chips). Opens with All selected for both.",
      "Independent pagination per column (Show 25/50/100 in the toolbar).",
      "Click a card to open docs/us/US-XXXX.md beside the board.",
      "Tab title: Board — {project or docs path} (N). Active project is saved across reopens.",
    ],
    icon: "$(layout)",
    status: "shipped",
  },
  {
    id: "versions",
    title: "Open Versions",
    commandId: "meridian.openVersions",
    paletteTitle: "Meridian: Open Versions",
    group: "views",
    summary: "Lists all releases in docs/versions/",
    details: [
      "Project row in toolbar — same active docs/ as Board.",
      "Accordion per version with progress (US done/total).",
      "No version filter — shows the full catalog.",
      "Footer pagination (Show 25/50/100).",
      "Click an id to open the version .md file.",
    ],
    icon: "$(versions)",
    status: "shipped",
  },
  {
    id: "sprints",
    title: "Open Sprints",
    commandId: "meridian.openSprints",
    paletteTitle: "Meridian: Open Sprints",
    group: "views",
    summary: "Lists sprints in docs/sprints/ filtered by version",
    details: [
      "Project row in toolbar — same active docs/ as Board.",
      "All / None / chip filter (same pattern as the Board).",
      "Opens with all versions selected; sorted by id (v4-S1, v4-S2…).",
      "Footer pagination.",
    ],
    icon: "$(run-all)",
    status: "shipped",
  },
  {
    id: "epics",
    title: "Open Epics",
    commandId: "meridian.openEpics",
    paletteTitle: "Meridian: Open Epics",
    group: "views",
    summary: "Lists epics with stories in the selected version scope",
    details: [
      "Project row in toolbar — same active docs/ as Board.",
      "Version filter only (All / None / chips).",
      "Progress bar per epic (US ✅ / total).",
      "Footer pagination.",
    ],
    icon: "$(layers)",
    status: "shipped",
  },
  {
    id: "deliverables",
    title: "Open Deliverables",
    commandId: "meridian.openDeliverables",
    paletteTitle: "Meridian: Open Deliverables",
    group: "views",
    summary: "Alias for Open Versions (v4 compatibility)",
    details: ["Same tab and behavior as Open Versions."],
    icon: "$(list-tree)",
    status: "shipped",
  },
  {
    id: "validate",
    title: "Validate project",
    commandId: "meridian.validateProject",
    paletteTitle: "Meridian: Validate Project",
    group: "governance",
    summary: "Runs validate_meridian.py on the project root",
    details: [
      "Equivalent to python3 .agent/scripts/validate_meridian.py <project-folder>.",
      "Checks docs/ structure, user stories, board.json, template contracts, etc.",
      "Pass/fail notification; full log in Output.",
    ],
    outputChannel: "Meridian Validate",
    icon: "$(checklist)",
    status: "shipped",
  },
  {
    id: "sync",
    title: "Sync board",
    commandId: "meridian.syncBoard",
    paletteTitle: "Meridian: Sync Board",
    group: "governance",
    summary: "Regenerates docs/kanban/board.json from US frontmatter",
    details: [
      "The Board **reads docs/us/** directly — sync is not required to view the kanban.",
      "Required for validate, CI, and tools that consume board.json.",
      "Refreshes open panels after writing.",
    ],
    outputChannel: "Meridian Tools",
    icon: "$(sync)",
    status: "shipped",
  },
  {
    id: "select-project",
    title: "Select active project",
    commandId: "meridian.selectActiveProject",
    paletteTitle: "Meridian: Select Active Project",
    group: "governance",
    summary: "Switch which docs/ tree is active when the repo has several",
    details: [
      "Discovery finds every folder named docs with Meridian fingerprint (00_scope or us/).",
      "Manifest .meridian/projects.json declares ids, names, default, and exclude.",
      "Same persistence as Board toolbar dropdown and status bar — choice saved per kit root.",
      "Board, Deliverables, validate, and sync use the active project only.",
    ],
    icon: "$(list-selection)",
    status: "shipped",
  },
  {
    id: "status",
    title: "Workspace status",
    commandId: "meridian.showStatus",
    paletteTitle: "Meridian: Show Workspace Status",
    group: "governance",
    summary: "Shows kit root, active project, and all resolved docs/ paths",
    details: [
      "Kit root (where .agent/MERIDIAN.md lives).",
      "Active docs/ path — any package layout (docs, apps/pkg/docs, etc.).",
      "Lists all Meridian projects when more than one docs/ exists.",
    ],
    outputChannel: "Meridian Tools",
    icon: "$(info)",
    status: "shipped",
  },
  {
    id: "agents-help",
    title: "Open Agents Help",
    commandId: "meridian.openAgentsHelp",
    paletteTitle: "Meridian: Open Agents Help",
    group: "kit",
    summary: "Reference tab — agent groups, slash commands, and steps 1–17",
    details: [
      "Same pattern as Command Help: read-only webview tab in the editor.",
      "Reads .agent/references/agents-help.md from the project root at runtime.",
      "Complements Command Help (extension commands) and the /agents-help slash command.",
    ],
    icon: "$(book)",
    status: "shipped",
  },
  {
    id: "new-us",
    title: "New user story",
    commandId: "meridian.newUserStory",
    paletteTitle: "Meridian: New User Story",
    group: "planned",
    summary: "User story creation wizard — planned for v5",
    details: [
      "Today: Output message instructing you to use /create-us in Cursor.",
      "v5: guided form aligned with the Meridian kit.",
    ],
    outputChannel: "Meridian Tools",
    icon: "$(add)",
    status: "stub",
  },
]
