export type CommandHelpEntry = {
  id: string
  title: string
  commandId: string
  paletteTitle: string
  group: "guides" | "views" | "governance" | "kit"
  summary: string
  details: string[]
  outputChannel?: string
  icon?: string
  status: "shipped" | "stub"
}

export const COMMAND_HELP_GROUPS: { id: CommandHelpEntry["group"]; label: string }[] = [
  { id: "guides", label: "Guides — read in this order" },
  { id: "views", label: "Views (editor tabs)" },
  { id: "governance", label: "Governance & diagnostics" },
  { id: "kit", label: "Kit setup" },
]

export const MERIDIAN_COMMAND_CATALOG: CommandHelpEntry[] = [
  {
    id: "welcome",
    title: "Welcome (first-value checklist)",
    commandId: "meridian.openWelcome",
    paletteTitle: "Meridian: Open Welcome",
    group: "guides",
    summary: "Onboarding checklist — kit, docs, delivery DB, adapters, board",
    details: [
      "Binary first-value target for new workspaces (see ide-integration.md).",
      "Orchestration stays in chat: /deus-ex dispatches specialist agents.",
    ],
    icon: "$(rocket)",
    status: "shipped",
  },
  {
    id: "guide-how-to",
    title: "How to use (start here)",
    commandId: "meridian.openHowToUse",
    paletteTitle: "Meridian: Open How to Use",
    group: "guides",
    summary: "Entry guide — extension vs chat, skills, setup, reading order",
    details: [
      "Kit file: .agent/references/guides/how-to-use.md — single human entry point.",
      "You type skill slashes (/us-create) or @agent. Procedures live in .agent/skills/.",
    ],
    icon: "$(lightbulb)",
    status: "shipped",
  },
  {
    id: "guide-start-here",
    title: "Concepts (start here)",
    commandId: "meridian.openStartHere",
    paletteTitle: "Meridian: Open Concepts",
    group: "guides",
    summary: "Phases, gates, folders — mental model only",
    details: [
      "No command lists — recipes are in the usage guide; commands in agents help.",
      "Kit file: .agent/references/guides/start-here.md",
    ],
    icon: "$(home)",
    status: "shipped",
  },
  {
    id: "guide-usage",
    title: "Usage guide (recipes)",
    commandId: "meridian.openUsageGuide",
    paletteTitle: "Meridian: Open Usage Guide",
    group: "guides",
    summary: "Situation → steps: new project, brownfield, implement, close US",
    details: [
      "Kit file: .agent/references/guides/usage-guide.md",
    ],
    icon: "$(list-unordered)",
    status: "shipped",
  },
  {
    id: "agents-help",
    title: "Agents & slash commands (reference)",
    commandId: "meridian.openAgentsHelp",
    paletteTitle: "Meridian: Open Agents Help",
    group: "guides",
    summary: "Lookup: all /commands, agent groups, steps 1–20",
    details: [
      "Use Ctrl+F — not meant as a linear tutorial.",
      "Kit file: .agent/references/guides/agents-help.md",
    ],
    icon: "$(book)",
    status: "shipped",
  },
  {
    id: "guide-extension-commands",
    title: "Extension commands (this catalog)",
    commandId: "meridian.openHelp",
    paletteTitle: "Meridian: Extension Commands",
    group: "guides",
    summary: "Palette commands for board, validate, kit install — not chat slash commands",
    details: [
      "Opens this help tab listing extension-only commands.",
      "Chat skills (/us-create, /project-status) and @agents — see agents-help.md.",
    ],
    icon: "$(symbol-event)",
    status: "shipped",
  },
  {
    id: "install-kit",
    title: "Install harness",
    commandId: "meridian.installKit",
    paletteTitle: "Meridian: Install Harness",
    group: "kit",
    summary: "Copy bundled Meridian kit (.agent/) into the workspace",
    details: [
      "Manual only — run from status bar, Command Palette, or Meridian → Commands.",
      "Copies agents, skills, and scripts from the VSIX bundle.",
      "Syncs .cursor/, .claude/, Codex, and .opencode/ IDE adapters via sync_kit.sh.",
      "After install: run /init-meridian in chat if docs/ does not exist yet.",
    ],
    outputChannel: "Meridian Tools",
    icon: "$(cloud-download)",
    status: "shipped",
  },
  {
    id: "upgrade-kit",
    title: "Upgrade harness",
    commandId: "meridian.upgradeKit",
    paletteTitle: "Meridian: Upgrade Harness",
    group: "kit",
    summary: "Replace existing .agent/ with the bundled kit version",
    details: [
      "Overwrites .agent/ and re-runs adapter sync.",
      "Creates .agent.backup-<timestamp>/ before overwrite when upgrading.",
      "Status bar shows harness A → B when this folder is behind the extension.",
      "A prompt lists installed vs bundled version once per extension version (Later dismisses that bump).",
      "Writes .agent/VERSION so later reloads can compare. Kit source repo (this monorepo) is not prompted.",
    ],
    outputChannel: "Meridian Tools",
    icon: "$(cloud-upload)",
    status: "shipped",
  },
  {
    id: "uninstall-kit",
    title: "Remove harness",
    commandId: "meridian.uninstallKit",
    paletteTitle: "Meridian: Remove Harness",
    group: "kit",
    summary: "Uninstall Meridian adapters (optionally .agent/) via uninstall-meridian-kit.sh",
    details: [
      "Adapters only (safe): removes Meridian links in .cursor/, .claude/, Codex, .opencode/.",
      "Full removal: adapters + .agent/ + gitignore entries.",
      "docs/ and .meridian/ (delivery SQLite) are never deleted — remove manually if desired.",
      "Requires kit ≥ 1.1.49 (uninstall-meridian-kit.sh).",
    ],
    outputChannel: "Meridian Tools",
    icon: "$(trash)",
    status: "shipped",
  },
  {
    id: "board",
    title: "Open Board",
    commandId: "meridian.openBoard",
    paletteTitle: "Meridian: Open Board",
    group: "views",
    summary: "Read-only kanban from SQLite",
    details: [
      "Use the board to see status — edit delivery via slash commands or kit CLI.",
      "Project row (first toolbar line): active name, docs/ path, US count; dropdown when several products.",
      "Columns: 📋 Backlog · 📌 Todo · 🔨 Doing · 🔶 Partial · 🧪 Tests · ✅ Done (from status + ready + in_progress); toggles 🧊 Frozen · 🚫 Deprecated.",
      "Click a card to open HTML preview; Edit opens a structured form backed by SQLite.",
    ],
    icon: "$(layout)",
    status: "shipped",
  },
  {
    id: "local-html-board",
    title: "Open local HTML board",
    commandId: "meridian.openLocalHtmlBoard",
    paletteTitle: "Meridian: Open local HTML board",
    group: "views",
    summary: "Spawn kit python3 serve in a terminal (same HTML as clone without VSIX)",
    details: [
      "Runs .agent/scripts/meridian_board_serve.py on the active packageRoot.",
      "Does not start on extension activate. Ctrl+C in that terminal stops the process.",
      "Source of truth is the kit folder, not a copy inside the extension.",
    ],
    icon: "$(globe)",
    status: "shipped",
  },
  {
    id: "versions",
    title: "Open Versions",
    commandId: "meridian.openVersions",
    paletteTitle: "Meridian: Open Versions",
    group: "views",
    summary: "Lists releases from SQLite delivery store",
    details: [
      "Project row in toolbar — same active docs/ as Board.",
      "Accordion per version with progress (US done/total).",
    ],
    icon: "$(versions)",
    status: "shipped",
  },
  {
    id: "sprints",
    title: "Open Sprints",
    commandId: "meridian.openSprints",
    paletteTitle: "Meridian: Open Sprints",
    group: "views",
    summary: "Lists sprints filtered by version",
    details: [
      "Project row in toolbar — same active docs/ as Board.",
      "All / None / chip filter (same pattern as the Board).",
    ],
    icon: "$(run-all)",
    status: "shipped",
  },
  {
    id: "epics",
    title: "Open Epics",
    commandId: "meridian.openEpics",
    paletteTitle: "Meridian: Open Epics",
    group: "views",
    summary: "Lists epics with stories in the selected version scope",
    details: [
      "Project row in toolbar — same active docs/ as Board.",
      "Version filter only (All / None / chips).",
      "Progress bar per epic (US done / total).",
    ],
    icon: "$(layers)",
    status: "shipped",
  },
  {
    id: "decisions",
    title: "Open Decisions",
    commandId: "meridian.openDecisions",
    paletteTitle: "Meridian: Open Decisions",
    group: "views",
    summary: "Read-only decision log from SQLite by date",
    details: [
      "Project row in toolbar — same active docs/ as Board.",
      "Accordion per calendar day; entries show time, title, what/why/impact.",
      "Click affected document to open the workspace file.",
      "Append via /update-decisions-log — not editable in the extension.",
    ],
    icon: "$(history)",
    status: "shipped",
  },
  {
    id: "architecture-diagram",
    title: "Open Architecture Diagram",
    commandId: "meridian.openArchitectureDiagram",
    paletteTitle: "Meridian: Open Architecture Diagram",
    group: "views",
    summary: "Interactive architecture maps from docs/architecture/diagrams (Mermaid .md / .mmd)",
    details: [
      "Reads Mermaid from docs/architecture/diagrams; Meridian renderer (theme + pan/zoom).",
      "Picker lists all diagram files (runtime, database ER, flows); optional Notes; open Source or linked phase doc.",
    ],
    icon: "$(type-hierarchy)",
    status: "shipped",
  },
  {
    id: "delivery-graph",
    title: "Open Delivery Graph",
    commandId: "meridian.openDeliveryGraph",
    paletteTitle: "Meridian: Open Delivery Graph",
    group: "views",
    summary: "US dependency topology from planning export (dependsOn edges)",
    details: [
      "Force-directed canvas with pan, zoom, and draggable nodes (Obsidian-style).",
      "Filtros laterais (mesmo padrão do board): versão e sprint com checkboxes.",
      "Click a node to open the US virtual document.",
      "Separate from the code import graph.",
    ],
    icon: "$(type-hierarchy-sub)",
    status: "shipped",
  },
  {
    id: "import-graph",
    title: "Open Import Graph",
    commandId: "meridian.openImportGraph",
    paletteTitle: "Meridian: Open Import Graph",
    group: "views",
    summary: "Scoped source import graph via kit CLI meridian_import_graph.py",
    details: [
      "Force-directed canvas scoped to the active Meridian project packageRoot.",
      "Nodes = source files; edges = static imports; click a node to open the file.",
      "Switch active project in the toolbar to rescan another package.",
    ],
    icon: "$(type-hierarchy-super)",
    status: "shipped",
  },
  {
    id: "deliverables",
    title: "Open Deliverables",
    commandId: "meridian.openDeliverables",
    paletteTitle: "Meridian: Open Deliverables",
    group: "views",
    summary: "Alias for Open Versions (v4 compatibility)",
    details: ["Same tab and behavior as Open Versions."],
    icon: "$(list-tree)",
    status: "shipped",
  },
  {
    id: "doctor",
    title: "Doctor (workspace health)",
    commandId: "meridian.doctor",
    paletteTitle: "Meridian: Doctor",
    group: "governance",
    summary: "Runs meridian_doctor.py — kit, docs, delivery DB, adapter parity",
    details: [
      "Defensive checks before delivery work — not a generic AI installer doctor.",
      "Equivalent to python3 .agent/scripts/meridian_doctor.py <project-root>.",
      "See .agent/references/protocol/ide-integration.md for IDE matrix and external harness notes.",
    ],
    outputChannel: "Meridian Doctor",
    icon: "$(heart)",
    status: "shipped",
  },
  {
    id: "validate",
    title: "Validate project",
    commandId: "meridian.validateProject",
    paletteTitle: "Meridian: Validate Project",
    group: "governance",
    summary: "Runs validate_meridian.py on the project root",
    details: [
      "Equivalent to python3 .agent/scripts/validate_meridian.py <project-folder>.",
      "Checks docs/ structure, SQLite delivery, template contracts, etc.",
      "Pass/fail notification; full log in Output.",
    ],
    outputChannel: "Meridian Validate",
    icon: "$(checklist)",
    status: "shipped",
  },
  {
    id: "select-project",
    title: "Select active project",
    commandId: "meridian.selectActiveProject",
    paletteTitle: "Meridian: Select Active Project",
    group: "governance",
    summary: "Switch which docs/ tree is active when the repo has several",
    details: [
      "Discovery finds every folder named docs with Meridian fingerprint (00_scope or meridian.db).",
      "Manifest .meridian/projects.json declares ids, names, default, and exclude.",
      "Board, Deliverables, validate use the active project only.",
    ],
    icon: "$(list-selection)",
    status: "shipped",
  },
  {
    id: "status",
    title: "Workspace status",
    commandId: "meridian.showStatus",
    paletteTitle: "Meridian: Show Workspace Status",
    group: "governance",
    summary: "Shows kit root, active project, and all resolved docs/ paths",
    details: [
      "Kit root (where .agent/MERIDIAN.md lives).",
      "Active docs/ path — any package layout (docs, apps/pkg/docs, etc.).",
      "Lists all Meridian projects when more than one docs/ exists.",
    ],
    outputChannel: "Meridian Tools",
    icon: "$(info)",
    status: "shipped",
  },
]
