export type CommandHelpEntry = {
  id: string
  title: string
  commandId: string
  paletteTitle: string
  group: "guides" | "views" | "governance" | "kit" | "planned"
  summary: string
  details: string[]
  outputChannel?: string
  icon?: string
  status: "shipped" | "stub"
}

export const COMMAND_HELP_GROUPS: { id: CommandHelpEntry["group"]; label: string }[] = [
  { id: "guides", label: "Guides — read in this order" },
  { id: "views", label: "Views (editor tabs)" },
  { id: "governance", label: "Governance & diagnostics" },
  { id: "kit", label: "Kit setup" },
  { id: "planned", label: "Planned (v5)" },
]

export const MERIDIAN_COMMAND_CATALOG: CommandHelpEntry[] = [
  {
    id: "guide-how-to",
    title: "How to use Meridian",
    commandId: "meridian.openHelp",
    paletteTitle: "Meridian: How to Use",
    group: "guides",
    summary: "Extension UI vs chat — what you click vs what you type",
    details: [
      "Opens this help tab with the full onboarding flow at the top.",
      "Rule of thumb: extension = see and validate docs/; chat slash commands = create and change docs/.",
      "You type workflows (/create-us). You do not need to @mention agents — workflows route them.",
    ],
    icon: "$(lightbulb)",
    status: "shipped",
  },
  {
    id: "guide-start-here",
    title: "Start here (concepts)",
    commandId: "meridian.openStartHere",
    paletteTitle: "Meridian: Open Start Here",
    group: "guides",
    summary: "Phases, artifacts, gates, and docs/ layout",
    details: [
      "Read first if Meridian is new — what is an epic, version, US, ready, Record.",
      "Kit file: .agent/references/start-here.md",
    ],
    icon: "$(home)",
    status: "shipped",
  },
  {
    id: "guide-usage",
    title: "Usage guide (situations)",
    commandId: "meridian.openUsageGuide",
    paletteTitle: "Meridian: Open Usage Guide",
    group: "guides",
    summary: "When to do what — new project, migrate, implement, close US",
    details: [
      "Situation → sequence table and step-by-step flows.",
      "Includes VS Code extension commands and how they pair with slash commands.",
      "Kit file: .agent/references/usage-guide.md",
    ],
    icon: "$(list-unordered)",
    status: "shipped",
  },
  {
    id: "agents-help",
    title: "Agents & slash commands",
    commandId: "meridian.openAgentsHelp",
    paletteTitle: "Meridian: Open Agents Help",
    group: "guides",
    summary: "Workflows, agents, skills, and steps 1–17",
    details: [
      "Slash commands (/status, /create-us) are workflows — you invoke these in chat.",
      "Agents (process-manager, board-keeper, …) are personas — routed by the workflow, or override with @agent.",
      "Skills are internal procedures — agents load them; you rarely type skill names.",
      "Kit file: .agent/references/agents-help.md",
    ],
    icon: "$(book)",
    status: "shipped",
  },
  {
    id: "install-kit",
    title: "Install harness",
    commandId: "meridian.installKit",
    paletteTitle: "Meridian: Install Harness",
    group: "kit",
    summary: "Copy bundled Meridian kit (.agent/) into the workspace",
    details: [
      "Manual only — run from status bar, Command Palette, or Meridian → Commands.",
      "Copies agents, skills, workflows, and scripts from the VSIX bundle.",
      "Syncs .cursor/, .claude/, and Codex IDE adapters via sync_cursor_kit.sh.",
      "After install: run /init-meridian in chat if docs/ does not exist yet.",
    ],
    outputChannel: "Meridian Tools",
    icon: "$(cloud-download)",
    status: "shipped",
  },
  {
    id: "upgrade-kit",
    title: "Upgrade harness",
    commandId: "meridian.upgradeKit",
    paletteTitle: "Meridian: Upgrade Harness",
    group: "kit",
    summary: "Replace existing .agent/ with the bundled kit version",
    details: [
      "Overwrites .agent/ and re-runs adapter sync.",
      "Use after updating the extension to pick up kit changes.",
    ],
    outputChannel: "Meridian Tools",
    icon: "$(cloud-upload)",
    status: "shipped",
  },
  {
    id: "board",
    title: "Open Board",
    commandId: "meridian.openBoard",
    paletteTitle: "Meridian: Open Board",
    group: "views",
    summary: "Read-only kanban from docs/us/*.md",
    details: [
      "Use the board to see status — not to edit stories (edit .md files or use slash commands).",
      "Project row (first toolbar line): active name, docs/ path, US count; dropdown when several products.",
      "Columns: Todo, Partial, Tests, Done, and Frozen (toggle).",
      "Click a card to open docs/us/US-XXXX.md beside the board.",
    ],
    icon: "$(layout)",
    status: "shipped",
  },
  {
    id: "versions",
    title: "Open Versions",
    commandId: "meridian.openVersions",
    paletteTitle: "Meridian: Open Versions",
    group: "views",
    summary: "Lists all releases in docs/versions/",
    details: [
      "Project row in toolbar — same active docs/ as Board.",
      "Accordion per version with progress (US done/total).",
      "Click an id to open the version .md file.",
    ],
    icon: "$(versions)",
    status: "shipped",
  },
  {
    id: "sprints",
    title: "Open Sprints",
    commandId: "meridian.openSprints",
    paletteTitle: "Meridian: Open Sprints",
    group: "views",
    summary: "Lists sprints in docs/sprints/ filtered by version",
    details: [
      "Project row in toolbar — same active docs/ as Board.",
      "All / None / chip filter (same pattern as the Board).",
    ],
    icon: "$(run-all)",
    status: "shipped",
  },
  {
    id: "epics",
    title: "Open Epics",
    commandId: "meridian.openEpics",
    paletteTitle: "Meridian: Open Epics",
    group: "views",
    summary: "Lists epics with stories in the selected version scope",
    details: [
      "Project row in toolbar — same active docs/ as Board.",
      "Version filter only (All / None / chips).",
      "Progress bar per epic (US ✅ / total).",
    ],
    icon: "$(layers)",
    status: "shipped",
  },
  {
    id: "deliverables",
    title: "Open Deliverables",
    commandId: "meridian.openDeliverables",
    paletteTitle: "Meridian: Open Deliverables",
    group: "views",
    summary: "Alias for Open Versions (v4 compatibility)",
    details: ["Same tab and behavior as Open Versions."],
    icon: "$(list-tree)",
    status: "shipped",
  },
  {
    id: "validate",
    title: "Validate project",
    commandId: "meridian.validateProject",
    paletteTitle: "Meridian: Validate Project",
    group: "governance",
    summary: "Runs validate_meridian.py on the project root",
    details: [
      "Equivalent to python3 .agent/scripts/validate_meridian.py <project-folder>.",
      "Checks docs/ structure, user stories, board.json, template contracts, etc.",
      "Pass/fail notification; full log in Output.",
    ],
    outputChannel: "Meridian Validate",
    icon: "$(checklist)",
    status: "shipped",
  },
  {
    id: "sync",
    title: "Sync board",
    commandId: "meridian.syncBoard",
    paletteTitle: "Meridian: Sync Board",
    group: "governance",
    summary: "Regenerates docs/kanban/board.json from US frontmatter",
    details: [
      "The Board reads docs/us/ directly — sync is not required to view the kanban.",
      "Run after /complete-us or when validate reports board drift.",
      "Refreshes open panels after writing.",
    ],
    outputChannel: "Meridian Tools",
    icon: "$(sync)",
    status: "shipped",
  },
  {
    id: "select-project",
    title: "Select active project",
    commandId: "meridian.selectActiveProject",
    paletteTitle: "Meridian: Select Active Project",
    group: "governance",
    summary: "Switch which docs/ tree is active when the repo has several",
    details: [
      "Discovery finds every folder named docs with Meridian fingerprint (00_scope or us/).",
      "Manifest .meridian/projects.json declares ids, names, default, and exclude.",
      "Board, Deliverables, validate, and sync use the active project only.",
    ],
    icon: "$(list-selection)",
    status: "shipped",
  },
  {
    id: "status",
    title: "Workspace status",
    commandId: "meridian.showStatus",
    paletteTitle: "Meridian: Show Workspace Status",
    group: "governance",
    summary: "Shows kit root, active project, and all resolved docs/ paths",
    details: [
      "Kit root (where .agent/MERIDIAN.md lives).",
      "Active docs/ path — any package layout (docs, apps/pkg/docs, etc.).",
      "Lists all Meridian projects when more than one docs/ exists.",
    ],
    outputChannel: "Meridian Tools",
    icon: "$(info)",
    status: "shipped",
  },
  {
    id: "new-us",
    title: "New user story",
    commandId: "meridian.newUserStory",
    paletteTitle: "Meridian: New User Story",
    group: "planned",
    summary: "User story creation wizard — planned for v5",
    details: [
      "Today: use /create-us in chat — not an extension form.",
      "v5: guided form aligned with the Meridian kit.",
    ],
    outputChannel: "Meridian Tools",
    icon: "$(add)",
    status: "stub",
  },
]
